services:
  - type: web
    name: face-recognition-api
    runtime: docker
    build:
      dockerfile: Dockerfile
    env: python
    envVars:
      - key: FLASK_ENV
        value: production
    port: 5000
command: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
